## Apriori Alogorithm

### Reading the transactions

In [17]:
import numpy as np
import pandas as pd

In [18]:
pd.read_csv("Order2.csv")

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
transactions = []
with open('Order1.csv','r') as file:
    for line in file:
        curr_trans = line.strip()
        tran_it = list(curr_trans.split(","))
        transactions.append(tran_it)
file.close()

In [20]:
from mlxtend.preprocessing import TransactionEncoder
TE = TransactionEncoder()
x  =  TE.fit_transform(transactions)
x

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [21]:
dataset = pd.DataFrame(x,columns = TE.columns_)
dataset

,01-01-2014,01-01-2015,01-02-2014,01-02-2015,01-03-2014,01-03-2015,01-04-2014,01-04-2015,01-05-2014,01-05-2015,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38761,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38762,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38763,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38764,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38765,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
from mlxtend.frequent_patterns import apriori,association_rules
apriori?

Signature:
apriori(
    df,
    min_support=0.5,
    use_colnames=False,
    max_len=None,
    verbose=0,
    low_memory=False,
)
Docstring:
Get frequent itemsets from a one-hot DataFrame

Parameters
-----------
df : pandas DataFrame
  pandas DataFrame the encoded format. Also supports
  DataFrames with sparse data; for more info, please
  see (https://pandas.pydata.org/pandas-docs/stable/
       user_guide/sparse.html#sparse-data-structures)

  Please note that the old pandas SparseDataFrame format
  is no longer supported in mlxtend >= 0.17.2.

  The allowed values are either 0/1 or True/False.
  For example,

```
         Apple  Bananas   Beer  Chicken   Milk   Rice
    0     True    False   True     True  False   True
    1     True    False   True    False  False   True
    2     True    False   True    False  False  False
    3     True     True  False    False  False  False
    4    False    False   True     True   True   True
    5    False    False   True    False   True   True
    6    False    False   True    False   True  False
    7     True     True  False    False  False  False
```

min_support : float (default: 0.5)
  A float between 0 and 1 for minumum support of the itemsets returned.
  The support is computed as the fraction
  `transactions_where_item(s)_occur / total_transactions`.

use_colnames : bool (default: False)
  If `True`, uses the DataFrames' column names in the returned DataFrame
  instead of column indices.

max_len : int (default: None)
  Maximum length of the itemsets generated. If `None` (default) all
  possible itemsets lengths (under the apriori condition) are evaluated.

verbose : int (default: 0)
  Shows the number of iterations if >= 1 and `low_memory` is `True`. If
  >=1 and `low_memory` is `False`, shows the number of combinations.

low_memory : bool (default: False)
  If `True`, uses an iterator to search for combinations above
  `min_support`.
  Note that while `low_memory=True` should only be used for large dataset
  if memory resources are limited, because this implementation is approx.
  3-6x slower than the default.


Returns
-----------
pandas DataFrame with columns ['support', 'itemsets'] of all itemsets
  that are >= `min_support` and < than `max_len`
  (if `max_len` is not None).
  Each itemset in the 'itemsets' column is of type `frozenset`,
  which is a Python built-in type that behaves similarly to
  sets except that it is immutable
  (For more info, see
  https://docs.python.org/3.6/library/stdtypes.html#frozenset).

Examples
-----------
For usage examples, please see
https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/
File:      ~/.local/lib/python3.10/site-packages/mlxtend/frequent_patterns/apriori.py
Type:      function

In [25]:
association_rules?

Signature:
association_rules(
    df,
    metric='confidence',
    min_threshold=0.8,
    support_only=False,
)
Docstring:
Generates a DataFrame of association rules including the
metrics 'score', 'confidence', and 'lift'

Parameters
-----------
df : pandas DataFrame
  pandas DataFrame of frequent itemsets
  with columns ['support', 'itemsets']

metric : string (default: 'confidence')
  Metric to evaluate if a rule is of interest.
  **Automatically set to 'support' if `support_only=True`.**
  Otherwise, supported metrics are 'support', 'confidence', 'lift',
  'leverage', 'conviction' and 'zhangs_metric'
  These metrics are computed as follows:

  - support(A->C) = support(A+C) [aka 'support'], range: [0, 1]

  - confidence(A->C) = support(A+C) / support(A), range: [0, 1]

  - lift(A->C) = confidence(A->C) / support(C), range: [0, inf]

  - leverage(A->C) = support(A->C) - support(A)*support(C),
    range: [-1, 1]

  - conviction = [1 - support(C)] / [1 - confidence(A->C)],
    range: [0, inf]

  - zhangs_metric(A->C) =
    leverage(A->C) / max(support(A->C)*(1-support(A)), support(A)*(support(C)-support(A->C)))
    range: [-1,1]


min_threshold : float (default: 0.8)
  Minimal threshold for the evaluation metric,
  via the `metric` parameter,
  to decide whether a candidate rule is of interest.

support_only : bool (default: False)
  Only computes the rule support and fills the other
  metric columns with NaNs. This is useful if:

  a) the input DataFrame is incomplete, e.g., does
  not contain support values for all rule antecedents
  and consequents

  b) you simply want to speed up the computation because
  you don't need the other metrics.

Returns
----------
pandas DataFrame with columns "antecedents" and "consequents"
  that store itemsets, plus the scoring metric columns:
  "antecedent support", "consequent support",
  "support", "confidence", "lift",
  "leverage", "conviction"
  of all rules for which
  metric(rule) >= min_threshold.
  Each entry in the "antecedents" and "consequents" columns are
  of type `frozenset`, which is a Python built-in type that
  behaves similarly to sets except that it is immutable
  (For more info, see
  https://docs.python.org/3.6/library/stdtypes.html#frozenset).

Examples
-----------
For usage examples, please see
https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/
File:      ~/.local/lib/python3.10/site-packages/mlxtend/frequent_patterns/association_rules.py
Type:      function